# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

name: Aditya Narayan
description: Blog of Aditya Narayan
url: "https://narayanaditya.in"

# Author info
author_name: Aditya Narayan
author_image_path: /images/author-image.jpeg

# External services
github_url: https://github.com/aditnryn
linkedin_url: https://www.linkedin.com/in/aditnryn
twitter_url: https://twitter.com/aditnryn
instagram_url: http://instagram.com/aditnryn
email: mail@narayanaditya.in

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Site settings
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
highlighter: rouge

# important since the site is compiled
# on Github's servers
timezone: Asia/Kolkata
